name: Generate Snake Contribution Graph

on:
  schedule:
    - cron: "0 0 * * *"  # Roda todo dia à meia-noite
  workflow_dispatch:  # Permite rodar manualmente no Actions

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: Devwillmarinho
          outputs: |
            ./output/snake.svg
            ./output/snake-dark.svg

      - name: Commit and Push
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: "Generate Snake Contribution Graph"
          add: "./output/snake.svg ./output/snake-dark.svg"
